# -*- coding: utf-8 -*-
"""training_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2D086ZAqomMvs9cFGZzCDQh7BXWjYSf

# Cell 1: 一键配置环境 + 拉取 Dave 的修复版代码
"""

# ==============================================================================
# Cell 1: 一键配置环境 + 拉取 Dave 的修复版代码
# ==============================================================================
import os
import time
import shutil

# --- 1. 安装基础环境 (Conda) ---
print("⏳ 正在安装 Conda...")
try:
    import condacolab
except ImportError:
    !pip install -q condacolab
    import condacolab
condacolab.install()
time.sleep(5)

print("✅ Conda 就绪！配置 Python 3.9 + JAX...")

# --- 2. 配置 Python 环境 (锁死版本) ---
!conda create -n mobilenerf python=3.9 -y
# 安装 CUDA, JAX, Flax (必须严格匹配)
!source activate mobilenerf && conda install -c conda-forge cudatoolkit=11.8 cudnn=8.8 -y
!source activate mobilenerf && pip install "jax[cuda11_pip]==0.3.25" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html --no-deps
!source activate mobilenerf && pip install "flax==0.5.3" scipy "optax==0.1.4" "chex==0.1.5" "absl-py" --no-deps
!source activate mobilenerf && pip install tqdm opencv-python-headless matplotlib gin-config msgpack typing-extensions opt_einsum toolz rich PyYAML numpy==1.23.5


print("✅ 运行环境搭建完毕！")

# --- 3. 拉取你的 GitHub 代码 (jax3d_David) ---
# 你的仓库地址
MY_REPO = "https://github.com/Davecodingking/jax3d_David.git"
TARGET_DIR = "/content/jax3d"

print(f"🚀 正在拉取你的代码: {MY_REPO}")

# 清理旧目录
if os.path.exists(TARGET_DIR): shutil.rmtree(TARGET_DIR)
if os.path.exists("/content/jax3d_David"): shutil.rmtree("/content/jax3d_David")

# 克隆仓库
!git clone {MY_REPO}

# 结构修正: 把 jax3d_David 改名为 jax3d (Python 才能识别)
if os.path.exists("/content/jax3d_David"):
    shutil.move("/content/jax3d_David", TARGET_DIR)
    print("✅ 代码已就位 (jax3d_David -> jax3d)")
else:
    print("❌ 克隆失败，请检查 GitHub 仓库是否为空或地址错误。")

print("🎉 准备就绪！请上传数据包 MyNeRFData.zip 并运行下一步。")

"""# Cell 2-Drive: 从 Google Drive 复制 MyNeRFData.zip"""

"""# Cell 2-Drive: 从 Google Drive 复制 MyNeRFData.zip（可选）"""

import os
from google.colab import drive

drive_zip_path = "/content/drive/MyDrive/MyNeRFData.zip"
local_zip_path = "/content/MyNeRFData.zip"

print("📂 [可选] 正在检查 Drive 上是否已有 MyNeRFData.zip ...")

if not os.path.exists("/content/drive"):
    drive.mount("/content/drive")

if os.path.exists(local_zip_path):
    print(f"✅ 本地已存在 {local_zip_path}，跳过从 Drive 复制。")
elif os.path.exists(drive_zip_path):
    print(f"🔄 在 Drive 找到数据集: {drive_zip_path}")
    print("   -> 正在复制到本地 /content/MyNeRFData.zip ...")
    os.system(f"cp '{drive_zip_path}' '{local_zip_path}'")
    print("✅ 复制完成！可以直接运行解压 Cell。")
else:
    print("⚠️ Drive 中未找到 MyNeRFData.zip。")
    print("   -> 若需要远程加载，请先把数据集上传到: MyDrive/MyNeRFData.zip")
    print("   -> 或者按原流程，在左侧文件栏手动上传到 /content/MyNeRFData.zip")

"""# Cell 3: 数据准备（解压 Dataset + 结构修复 + 挂载 Drive）"""

# ==========================================
# 步骤 2 (修复版): 智能解压与完整性检查
# 说明：请保证 ZIP 内部顶层文件夹命名为 MyNeRFData，
#       且最终展开路径为 data/custom/MyNeRFData，对应 mobilenerf 中 object_name="MyNeRFData"
# ==========================================
import os
import zipfile

zip_path = '/content/MyNeRFData.zip'
extract_path = '/content/jax3d/jax3d/projects/mobilenerf/data/custom/MyNeRFData'

# 1. 检查文件是否存在
if not os.path.exists(zip_path):
    print("❌ 错误：根本没找到 /content/MyNeRFData.zip！")
    print("👉 请将文件拖入左侧文件栏，并等待上传完成。")
    assert False

# 2. 检查文件是否损坏 (关键步骤)
if not zipfile.is_zipfile(zip_path):
    print("❌ 致命错误：ZIP 文件已损坏或未上传完成！")
    print("💡 原因：通常是因为你在上传进度条走完之前就点击了运行。")
    print("👉 解决：请在左侧删除该文件，重新上传，务必等待下方进度圈完全消失！")
    # 打印文件大小看看
    file_size = os.path.getsize(zip_path) / (1024 * 1024)
    print(f"   当前文件大小仅为: {file_size:.2f} MB (如果这个数很小，说明肯定没传完)")
    assert False

print(f"✅ ZIP 文件完整 ({os.path.getsize(zip_path)/1024/1024:.2f} MB)。准备解压...")

# 3. 创建目录
if not os.path.exists(extract_path):
    os.makedirs(extract_path)

# 4. 解压
print(f"📂 正在解压到: {extract_path}")
# 使用 python 自带库解压，比 shell 命令更稳
try:
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("✅ 解压成功！")
except Exception as e:
    print(f"❌ 解压失败: {e}")
    assert False

# 5. 再次核实内容
# 有时候 zip 包里自带了一层文件夹，我们需要确认 json 在哪
print("🧐 核实文件位置...")
found_json = False
for root, dirs, files in os.walk(extract_path):
    if "transforms_train.json" in files:
        print(f"✅ 成功找到配置文件: {os.path.join(root, 'transforms_train.json')}")
        found_json = True
        break

if not found_json:
    print("⚠️ 警告：解压成功，但没找到 transforms_train.json。")
    print("👇 请检查下面的文件结构，看看是不是套了一层文件夹？")
    for root, dirs, files in os.walk(extract_path):
        level = root.replace(extract_path, '').count(os.sep)
        indent = ' ' * 4 * (level)
        print('{}{}/'.format(indent, os.path.basename(root)))
        subindent = ' ' * 4 * (level + 1)
        for f in files[:5]: # 只显示前5个文件
            print('{}{}'.format(subindent, f))
else:
    print("🎉 数据准备完美就绪！请继续运行 Step 3。")

import os
import shutil

nested_dir = '/content/jax3d/jax3d/projects/mobilenerf/data/custom/MyNeRFData/MyNeRFData'
target_dir = '/content/jax3d/jax3d/projects/mobilenerf/data/custom/MyNeRFData'

print("🔧 正在检测是否套娃...")

if os.path.exists(nested_dir):
    print(f"⚠️ 发现套娃文件夹！正在把文件从 {nested_dir} 搬出来...")

    # 遍历套娃文件夹里的所有文件，移动到外面
    for filename in os.listdir(nested_dir):
        src = os.path.join(nested_dir, filename)
        dst = os.path.join(target_dir, filename)

        # 如果目标已存在，先删除，防止报错
        if os.path.exists(dst):
            if os.path.isdir(dst): shutil.rmtree(dst)
            else: os.remove(dst)

        shutil.move(src, dst)
        print(f"  -> 移动: {filename}")

    # 删掉空的套娃壳子
    os.rmdir(nested_dir)
    print("✅ 搬家完成！结构已修复。")
else:
    print("ℹ️ 没发现套娃文件夹。")
    # 检查一下文件到底在哪
    if os.path.exists(os.path.join(target_dir, "transforms_train.json")):
        print("✅ 确认：json 文件已经在正确位置了。")
    else:
        print("❌ 依然找不到文件，请检查左侧文件栏确认路径。")

import os
import time
import threading
import shutil
import re
from google.colab import drive
from IPython import get_ipython

# 1. 环境准备
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

project_dir = '/content/jax3d/jax3d/projects/mobilenerf'
if os.path.exists(project_dir):
    os.chdir(project_dir)
    os.environ['PYTHONPATH'] += ":/content/jax3d"
else:
    print(f"❌ 找不到项目目录: {project_dir}")

"""# Cell 4: 环境配置 （PyTorch 2.1 + NumPy 1.26 + PyTorch3D Wheel）

"""

"""# Cell 8-UV: 01_preprocess_raster 专用环境（Wheel加速 + NumPy修复版）"""

import os

# 1. 创建环境 (Python 3.10)
print("🚀 [Hybrid UV Env] 正在创建 Python 3.10 环境...")
!conda create -n hybrid_uv_wheel python=3.10 -y

# 2. 安装 PyTorch 2.1.0 + CUDA 11.8 + ★NumPy 1.26.4★
# 关键修复：显式加上 numpy=1.26.4，防止安装 NumPy 2.x
print("⏳ 正在安装 PyTorch 2.1.0 和 NumPy 1.26.4...")
!source activate hybrid_uv_wheel && conda install -y \
    pytorch=2.1.0 torchvision=0.16.0 torchaudio=2.1.0 \
    pytorch-cuda=11.8 \
    numpy=1.26.4 \
    -c pytorch -c nvidia

# 3. 安装依赖 (fvcore, iopath)
# 使用 pip 安装时也限制 numpy 版本，防止被升级
print("⏳ 正在安装基础依赖...")
!source activate hybrid_uv_wheel && pip install "numpy<2" fvcore iopath matplotlib pillow


# 4. 安装 PyTorch3D 官方 Wheel 包 (GPU 加速核心)
print("⏳ 正在安装 PyTorch3D 官方加速包...")
!source activate hybrid_uv_wheel && pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu118_pyt210/download.html

print("\n✅ 环境配置完成！NumPy版本已锁定，CUDA加速已就绪。")

"""# Cell 8: Hybrid Workflow 环境配置（基于 Colab 默认环境）"""

print("\n🚀 [Hybrid Env] 配置 Torch + PyTorch3D 环境（使用 Colab 默认 Python）...")
!pip install --upgrade pip
!pip install "numpy<2"
!pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html

# !pip install --upgrade pip
# !pip install "numpy<2" --force-reinstall
# !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html

"""# Cell 5: Overlay 检查 无反转"""

import os

# 定义对比脚本内容
diagnostic_script = r'''
import os
import json
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from pytorch3d.io import load_obj
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    PerspectiveCameras, RasterizationSettings, MeshRasterizer,
    MeshRenderer, SoftPhongShader, AmbientLights, TexturesVertex
)

# ================= CONFIG =================
DATA_ROOT = "data/custom/MyNeRFData"
OBJ_NAME = "sponza_gt.obj"
TRANSFORMS = "transforms_train.json"
DEVICE = "cuda"
TARGET_FRAMES = [0, 29] # 第 1 帧 和 第 30 帧
# ==========================================

def run_comparison():
    print(f"🚀 启动结构对比诊断: 检查 Index {TARGET_FRAMES}...")

    # 1. 加载模型
    obj_path = os.path.join(DATA_ROOT, OBJ_NAME)
    verts, faces, _ = load_obj(obj_path)
    verts = verts.to(DEVICE).float()
    faces_idx = faces.verts_idx.to(DEVICE).long()

    # 法线着色：观察几何轮廓
    temp_mesh = Meshes(verts=[verts], faces=[faces_idx])
    normals = temp_mesh.verts_normals_packed()
    verts_rgb = (normals + 1.0) / 2.0
    textures = TexturesVertex(verts_features=verts_rgb[None])
    mesh = Meshes(verts=[verts], faces=[faces_idx], textures=textures)

    # 2. 加载元数据
    with open(os.path.join(DATA_ROOT, TRANSFORMS), "r") as f:
        meta = json.load(f)

    camera_angle_x = float(meta["camera_angle_x"])
    lights = AmbientLights(device=DEVICE, ambient_color=((1.0, 1.0, 1.0),))

    results = []

    for idx in TARGET_FRAMES:
        frame = meta["frames"][idx]
        img_path = os.path.join(DATA_ROOT, frame["file_path"] + ".png")
        if not os.path.exists(img_path):
            img_path = img_path.replace(".png", ".jpg")

        gt_image = np.array(Image.open(img_path).convert("RGB")) / 255.0
        H, W, _ = gt_image.shape

        c2w = np.array(frame["transform_matrix"], dtype=np.float32)
        c2w_t = torch.from_numpy(c2w).to(DEVICE)

        R_c2w = c2w_t[:3, :3]
        C = c2w_t[:3, 3]
        R_w2c = R_c2w.t()
        T_w2c = -R_w2c @ C

        focal = 0.5 * W / np.tan(0.5 * camera_angle_x)
        cameras = PerspectiveCameras(
            device=DEVICE,
            R=R_w2c.t().unsqueeze(0), # PyTorch3D 内部使用行向量乘法，所以传转置
            T=T_w2c.unsqueeze(0),
            focal_length=((focal, focal),),
            principal_point=((W/2, H/2),),
            image_size=((H, W),),
            in_ndc=False
        )

        raster_settings = RasterizationSettings(image_size=(H, W), blur_radius=0.0, faces_per_pixel=1, cull_backfaces=False)
        renderer = MeshRenderer(
            rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
            shader=SoftPhongShader(device=DEVICE, cameras=cameras, lights=lights)
        )

        render_rgba = renderer(mesh)[0].cpu().numpy()
        render_rgb = render_rgba[..., :3]
        results.append((gt_image, render_rgb, idx))

    fig, axes = plt.subplots(2, 2, figsize=(20, 16))
    for i, (gt, ren, idx) in enumerate(results):
        axes[i, 0].imshow(gt)
        axes[i, 0].set_title(f"Frame {idx}: Unity Photo", fontsize=16)
        axes[i, 0].axis("off")

        axes[i, 1].imshow(ren)
        axes[i, 1].set_title(f"Frame {idx}: Pytorch3D Render (Raw)", fontsize=16)
        axes[i, 1].axis("off")

    plt.tight_layout()
    output_name = "frame_comparison_result.png"
    plt.savefig(output_name)
    print(f"✅ 对比图已生成: {output_name}")

if __name__ == "__main__":
    run_comparison()
'''

# 写入文件
with open("compare_script.py", "w") as f:
    f.write(diagnostic_script)

# 执行诊断
print("🚀 正在运行对比诊断...")
!source activate hybrid_uv_wheel && export MPLBACKEND=Agg && python compare_script.py

# 显示结果
from IPython.display import Image, display
if os.path.exists("frame_comparison_result.png"):
    display(Image("frame_comparison_result.png"))

"""# Cell 6:Hybrid Pipeline Step 1 - 预计算 UV (PyTorch3D)"""

"""# Cell 9: Hybrid Pipeline Step 1 - 预计算 UV (运行)"""

import os
from IPython import get_ipython
from google.colab import drive
import numpy as np

PROJECT_ROOT_HYBRID = "/content/jax3d/jax3d/projects/mobilenerf"
DRIVE_HYBRID_ROOT = "/content/drive/MyDrive/Hybrid_Pipeline"
HYBRID_DATA_ROOT = "data/custom/MyNeRFData"
HYBRID_OBJ_NAME = "sponza_gt_unwarpped.obj"
HYBRID_TRANSFORMS = "transforms_train.json"
HYBRID_UV_OUTPUT = "uv_lookup.npz"

print("\n🚀 [Hybrid 1/2] 预计算 UV 映射 (GPU 加速模式)...")

if not os.path.exists("/content/drive"):
    drive.mount("/content/drive")

if not os.path.exists(DRIVE_HYBRID_ROOT):
    os.makedirs(DRIVE_HYBRID_ROOT)

if os.path.exists(PROJECT_ROOT_HYBRID):
    os.chdir(PROJECT_ROOT_HYBRID)

    # 注意：这里激活的是 hybrid_uv_wheel 环境
    cmd = f"""
    source activate hybrid_uv_wheel && \
    python 01_preprocess_raster.py \
      --data_root='{HYBRID_DATA_ROOT}' \
      --obj_name='{HYBRID_OBJ_NAME}' \
      --transforms='{HYBRID_TRANSFORMS}' \
      --output='{HYBRID_UV_OUTPUT}' \
      --downscale=1 \
      --device='cuda'
    """

    get_ipython().system(f"bash -c '{cmd}'")

    uv_path = os.path.join(PROJECT_ROOT_HYBRID, HYBRID_DATA_ROOT, HYBRID_UV_OUTPUT)
    if os.path.exists(uv_path):
        data = np.load(uv_path, allow_pickle=True)
        print(f"✅ UV 映射生成完成，形状: {data['uv'].shape}")
        # 复制到 Google Drive 备份
        os.system(f"cp '{uv_path}' '{DRIVE_HYBRID_ROOT}/'")
        print(f"✅ 备份完成！现在去运行训练吧。")
    else:
        print("⚠️ 未找到 uv_lookup.npz，请检查上方报错")
else:
    print(f"❌ 找不到项目目录: {PROJECT_ROOT_HYBRID}")

"""# Cell 7.1: 使用 xatlas 修复 UV 重叠并导出 OBJ"""

"""# Cell 9.1: 使用 xatlas 修复 UV 重叠并导出 OBJ"""

print("\n🚀 [Hybrid 1/2 Extra] xatlas UV 重映射（保持顶点顺序/位置不变）...")
!source activate hybrid_uv_wheel && pip install xatlas trimesh

PROJECT_ROOT_HYBRID = "/content/jax3d/jax3d/projects/mobilenerf"
DRIVE_HYBRID_ROOT = "/content/drive/MyDrive/Hybrid_Pipeline"
HYBRID_DATA_ROOT = "data/custom/MyNeRFData"
HYBRID_OBJ_NAME = "sponza_gt.obj"

if os.path.exists(PROJECT_ROOT_HYBRID):
    os.chdir(PROJECT_ROOT_HYBRID)
    cmd = f"""
    source activate hybrid_uv_wheel && \
    python uv_unwrap_xatlas.py --input {HYBRID_DATA_ROOT}/{HYBRID_OBJ_NAME} --output {HYBRID_DATA_ROOT}/sponza_gt_unwarpped.obj
    """
    get_ipython().system(f"bash -c '{cmd}'")

    new_obj = os.path.join(PROJECT_ROOT_HYBRID, HYBRID_DATA_ROOT, "sponza_gt_unwarpped.obj")
    if os.path.exists(new_obj):
        print("✅ xatlas UV 重映射完成，已生成 sponza_gt_unwarpped.obj")
        os.system(f"cp '{new_obj}' '{DRIVE_HYBRID_ROOT}/'")
        print("✅ 已备份到 Drive")
    else:
        print("❌ xatlas 重映射输出不存在，请检查日志")
else:
    print(f"❌ 找不到项目目录: {PROJECT_ROOT_HYBRID}")

"""# Cell 7.2: 渲染对比测试 - render_comparison_test.py"""

import os
from IPython import get_ipython

PROJECT_ROOT_HYBRID = "/content/jax3d/jax3d/projects/mobilenerf"

print("\n🚀 [Hybrid 1/2 Extra] 运行 render_comparison_test.py 做几何一致性对比...")

if os.path.exists(PROJECT_ROOT_HYBRID):
    os.chdir(PROJECT_ROOT_HYBRID)
    cmd = """
    source activate hybrid_uv_wheel && \
    python render_comparison_test.py
    """
    get_ipython().system(f"bash -c '{cmd}'")
else:
    print(f"❌ 找不到项目目录: {PROJECT_ROOT_HYBRID}")

"""# Cell 8: Hybrid Pipeline Step 2 - 训练 Hybrid Texture + MLP"""

"""# Cell 11: Hybrid Pipeline Step 2 - 训练 Hybrid Texture + MLP"""

import os
import time
import threading
from IPython import get_ipython
from google.colab import drive

PROJECT_ROOT_HYBRID = "/content/jax3d/jax3d/projects/mobilenerf"
DRIVE_HYBRID_ROOT = "/content/drive/MyDrive/Hybrid_Pipeline"


HYBRID_DATA_ROOT_TRAIN = "data/custom/MyNeRFData"
HYBRID_UV_PATH_TRAIN = os.path.join(HYBRID_DATA_ROOT_TRAIN, "uv_lookup.npz")

HYBRID_TEXTURE_SIZE = 4096
HYBRID_BATCH_SIZE = 1024
HYBRID_NUM_ITERS = 150000
HYBRID_LR = 3e-4
HYBRID_DOWNSCALE_TRAIN = 1

HYBRID_CHECKPOINT_PATH = "weights/hybrid_texture_mlp.pth"
HYBRID_ENV_PYTHON = "python"

print("\n🚀 [Hybrid 2/2] 启动 Hybrid Texture + MLP 训练...")

if not os.path.exists("/content/drive"):
    drive.mount("/content/drive")

if not os.path.exists(DRIVE_HYBRID_ROOT):
    os.makedirs(DRIVE_HYBRID_ROOT)

local_weights = os.path.join(PROJECT_ROOT_HYBRID, "weights")
local_samples = os.path.join(PROJECT_ROOT_HYBRID, "samples")
dst_weights = os.path.join(DRIVE_HYBRID_ROOT, "weights")
dst_samples = os.path.join(DRIVE_HYBRID_ROOT, "samples")

def hybrid_background_backup():
    while True:
        try:
            if os.path.exists(local_weights):
                if not os.path.exists(dst_weights):
                    os.makedirs(dst_weights)
                os.system(f"cp -ru '{local_weights}/.' '{dst_weights}/'")
            if os.path.exists(local_samples):
                if not os.path.exists(dst_samples):
                    os.makedirs(dst_samples)
                os.system(f"cp -ru '{local_samples}/.' '{dst_samples}/'")
        except:
            pass
        time.sleep(60)

t = threading.Thread(target=hybrid_background_backup)
t.daemon = True
t.start()

local_uv_path = os.path.join(PROJECT_ROOT_HYBRID, HYBRID_UV_PATH_TRAIN)
drive_uv_path = os.path.join(DRIVE_HYBRID_ROOT, os.path.basename(HYBRID_UV_PATH_TRAIN))

if not os.path.exists(local_uv_path) and os.path.exists(drive_uv_path):
    os.makedirs(os.path.dirname(local_uv_path), exist_ok=True)
    os.system(f"cp '{drive_uv_path}' '{local_uv_path}'")
    print(f"🔄 已从 Drive 恢复 uv_lookup.npz 到本地: {local_uv_path}")

if os.path.exists(PROJECT_ROOT_HYBRID):
    os.chdir(PROJECT_ROOT_HYBRID)
    cmd = f"""
export MPLBACKEND=Agg && {HYBRID_ENV_PYTHON} 02_train_hybrid.py \
  --data_root='{HYBRID_DATA_ROOT_TRAIN}' \
  --uv_path='{HYBRID_UV_PATH_TRAIN}' \
  --texture_size={HYBRID_TEXTURE_SIZE} \
  --batch_size={HYBRID_BATCH_SIZE} \
  --num_iters={HYBRID_NUM_ITERS} \
  --lr={HYBRID_LR} \
  --device='auto' \
  --downscale={HYBRID_DOWNSCALE_TRAIN} \
  --checkpoint='{HYBRID_CHECKPOINT_PATH}'
"""
    get_ipython().system(cmd)

    print("\n📦 正在备份 Hybrid 训练结果到 Drive...")
    if not os.path.exists(DRIVE_HYBRID_ROOT):
        os.makedirs(DRIVE_HYBRID_ROOT)

    local_weights = os.path.join(PROJECT_ROOT_HYBRID, "weights")
    local_samples = os.path.join(PROJECT_ROOT_HYBRID, "samples")

    if os.path.exists(local_weights):
        dst_weights = os.path.join(DRIVE_HYBRID_ROOT, "weights")
        if not os.path.exists(dst_weights):
            os.makedirs(dst_weights)
        os.system(f"cp -ru '{local_weights}/.' '{dst_weights}/'")

    if os.path.exists(local_samples):
        dst_samples = os.path.join(DRIVE_HYBRID_ROOT, "samples")
        if not os.path.exists(dst_samples):
            os.makedirs(dst_samples)
        os.system(f"cp -ru '{local_samples}/.' '{dst_samples}/'")

    print(f"\n✅ Hybrid 训练结果已保存至: {DRIVE_HYBRID_ROOT}")
else:
    print(f"❌ 找不到项目目录: {PROJECT_ROOT_HYBRID}")
