# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zebqJlzfvhUNkDAkTDCtHpAvCtYDVgY5

# 可选参考块: 安装 Conda + 构建 Python 3.9 环境 + 克隆官方 jax3d（一般可以跳过）
# 说明: 仅当你需要对照官方原版仓库时再运行这一块；
#      常规训练建议直接从下方 Cell 1 开始，使用 jax3d_David 仓库。
"""

# -*- coding: utf-8 -*-
import os

print("⏳ 正在安装 Conda (可能需要 1-2 分钟)...")
!pip install -q condacolab
import condacolab
condacolab.install()

import time
time.sleep(5) # 给它一点时间反应
print("✅ Conda 安装完成！正在配置 Python 3.9 环境...")

# 创建环境并锁死 JAX 版本 (0.3.25)
!conda create -n mobilenerf python=3.9 -y
!source activate mobilenerf && conda install -c conda-forge cudatoolkit=11.8 cudnn=8.8 -y
# 使用 --no-deps 防止 pip 自动升级 JAX
!source activate mobilenerf && pip install "jax[cuda11_pip]==0.3.25" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html --no-deps
# 手动补齐 JAX 依赖
!source activate mobilenerf && pip install "flax==0.5.3" scipy "optax==0.1.4" "chex==0.1.5" "absl-py" --no-deps
# 安装其他工具
!source activate mobilenerf && pip install tqdm opencv-python-headless matplotlib gin-config msgpack typing-extensions opt_einsum toolz rich PyYAML numpy==1.23.5

# 下载代码
if not os.path.exists('/content/jax3d'):
    !git clone https://github.com/google-research/jax3d.git

print("✅ 环境搭建完毕！JAX 版本已锁死为 0.3.25")

"""# Cell 1: 一键配置环境 + 拉取 Dave 的修复版代码"""

# ==============================================================================
# Cell 1: 一键配置环境 + 拉取 Dave 的修复版代码
# ==============================================================================
import os
import time
import shutil

# --- 1. 安装基础环境 (Conda) ---
print("⏳ 正在安装 Conda...")
try:
    import condacolab
except ImportError:
    !pip install -q condacolab
    import condacolab
condacolab.install()
time.sleep(5)

print("✅ Conda 就绪！配置 Python 3.9 + JAX...")

# --- 2. 配置 Python 环境 (锁死版本) ---
!conda create -n mobilenerf python=3.9 -y
# 安装 CUDA, JAX, Flax (必须严格匹配)
!source activate mobilenerf && conda install -c conda-forge cudatoolkit=11.8 cudnn=8.8 -y
!source activate mobilenerf && pip install "jax[cuda11_pip]==0.3.25" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html --no-deps
!source activate mobilenerf && pip install "flax==0.5.3" scipy "optax==0.1.4" "chex==0.1.5" "absl-py" --no-deps
!source activate mobilenerf && pip install tqdm opencv-python-headless matplotlib gin-config msgpack typing-extensions opt_einsum toolz rich PyYAML numpy==1.23.5


print("✅ 运行环境搭建完毕！")

# --- 3. 拉取你的 GitHub 代码 (jax3d_David) ---
# 你的仓库地址
MY_REPO = "https://github.com/Davecodingking/jax3d_David.git"
TARGET_DIR = "/content/jax3d"

print(f"🚀 正在拉取你的代码: {MY_REPO}")

# 清理旧目录
if os.path.exists(TARGET_DIR): shutil.rmtree(TARGET_DIR)
if os.path.exists("/content/jax3d_David"): shutil.rmtree("/content/jax3d_David")

# 克隆仓库
!git clone {MY_REPO}

# 结构修正: 把 jax3d_David 改名为 jax3d (Python 才能识别)
if os.path.exists("/content/jax3d_David"):
    shutil.move("/content/jax3d_David", TARGET_DIR)
    print("✅ 代码已就位 (jax3d_David -> jax3d)")
else:
    print("❌ 克隆失败，请检查 GitHub 仓库是否为空或地址错误。")

print("🎉 准备就绪！请上传数据包 MyNeRFData.zip 并运行下一步。")

"""# Cell 2: 打包当前 jax3d 仓库（可选）"""

import shutil
import os
from google.colab import files

# 1. 定义打包目标：整个 jax3d 仓库 (包含修好的 mobilenerf)
source_dir = '/content/jax3d'
output_filename = '/content/jax3d_fixed_final'

print(f"📦 正在打包修复后的代码库: {source_dir} ...")
print("   (这包含了 Scale=0.033, No-Gamma, RGB-Fix 的所有修改)")

# 2. 压缩
shutil.make_archive(output_filename, 'zip', source_dir)

print(f"✅ 打包完成: {output_filename}.zip")
print("⬇️ 请在左侧文件栏找到 'jax3d_fixed_final.zip'，右键下载并妥善保存！")
# files.download(output_filename + '.zip') # 你可以手动取消注释让它自动下载

# --- 3. 拉取你的 GitHub 代码 (jax3d_David) ---
# 你的仓库地址
MY_REPO = "https://github.com/Davecodingking/jax3d_David.git"
TARGET_DIR = "/content/jax3d"

print(f"🚀 正在拉取你的代码: {MY_REPO}")

# 清理旧目录
if os.path.exists(TARGET_DIR): shutil.rmtree(TARGET_DIR)
if os.path.exists("/content/jax3d_David"): shutil.rmtree("/content/jax3d_David")

# 克隆仓库
!git clone {MY_REPO}

# 结构修正: 把 jax3d_David 改名为 jax3d (Python 才能识别)
if os.path.exists("/content/jax3d_David"):
    shutil.move("/content/jax3d_David", TARGET_DIR)
    print("✅ 代码已就位 (jax3d_David -> jax3d)")
else:
    print("❌ 克隆失败，请检查 GitHub 仓库是否为空或地址错误。")

print("🎉 准备就绪！请上传数据包 MyNeRFData.zip 并运行下一步。")

"""# Cell 2-Drive: 从 Google Drive 复制 MyNeRFData.zip（可选）"""

"""# Cell 2-Drive: 从 Google Drive 复制 MyNeRFData.zip（可选）"""

import os
from google.colab import drive

drive_zip_path = "/content/drive/MyDrive/MyNeRFData.zip"
local_zip_path = "/content/MyNeRFData.zip"

print("📂 [可选] 正在检查 Drive 上是否已有 MyNeRFData.zip ...")

if not os.path.exists("/content/drive"):
    drive.mount("/content/drive")

if os.path.exists(local_zip_path):
    print(f"✅ 本地已存在 {local_zip_path}，跳过从 Drive 复制。")
elif os.path.exists(drive_zip_path):
    print(f"🔄 在 Drive 找到数据集: {drive_zip_path}")
    print("   -> 正在复制到本地 /content/MyNeRFData.zip ...")
    os.system(f"cp '{drive_zip_path}' '{local_zip_path}'")
    print("✅ 复制完成！可以直接运行解压 Cell。")
else:
    print("⚠️ Drive 中未找到 MyNeRFData.zip。")
    print("   -> 若需要远程加载，请先把数据集上传到: MyDrive/MyNeRFData.zip")
    print("   -> 或者按原流程，在左侧文件栏手动上传到 /content/MyNeRFData.zip")

"""# Cell 3: 数据准备（解压 Dataset + 结构修复 + 挂载 Drive）"""

# ==========================================
# 步骤 2 (修复版): 智能解压与完整性检查
# 说明：请保证 ZIP 内部顶层文件夹命名为 MyNeRFData，
#       且最终展开路径为 data/custom/MyNeRFData，对应 mobilenerf 中 object_name="MyNeRFData"
# ==========================================
import os
import zipfile

zip_path = '/content/MyNeRFData.zip'
extract_path = '/content/jax3d/jax3d/projects/mobilenerf/data/custom/MyNeRFData'

# 1. 检查文件是否存在
if not os.path.exists(zip_path):
    print("❌ 错误：根本没找到 /content/MyNeRFData.zip！")
    print("👉 请将文件拖入左侧文件栏，并等待上传完成。")
    assert False

# 2. 检查文件是否损坏 (关键步骤)
if not zipfile.is_zipfile(zip_path):
    print("❌ 致命错误：ZIP 文件已损坏或未上传完成！")
    print("💡 原因：通常是因为你在上传进度条走完之前就点击了运行。")
    print("👉 解决：请在左侧删除该文件，重新上传，务必等待下方进度圈完全消失！")
    # 打印文件大小看看
    file_size = os.path.getsize(zip_path) / (1024 * 1024)
    print(f"   当前文件大小仅为: {file_size:.2f} MB (如果这个数很小，说明肯定没传完)")
    assert False

print(f"✅ ZIP 文件完整 ({os.path.getsize(zip_path)/1024/1024:.2f} MB)。准备解压...")

# 3. 创建目录
if not os.path.exists(extract_path):
    os.makedirs(extract_path)

# 4. 解压
print(f"📂 正在解压到: {extract_path}")
# 使用 python 自带库解压，比 shell 命令更稳
try:
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("✅ 解压成功！")
except Exception as e:
    print(f"❌ 解压失败: {e}")
    assert False

# 5. 再次核实内容
# 有时候 zip 包里自带了一层文件夹，我们需要确认 json 在哪
print("🧐 核实文件位置...")
found_json = False
for root, dirs, files in os.walk(extract_path):
    if "transforms_train.json" in files:
        print(f"✅ 成功找到配置文件: {os.path.join(root, 'transforms_train.json')}")
        found_json = True
        break

if not found_json:
    print("⚠️ 警告：解压成功，但没找到 transforms_train.json。")
    print("👇 请检查下面的文件结构，看看是不是套了一层文件夹？")
    for root, dirs, files in os.walk(extract_path):
        level = root.replace(extract_path, '').count(os.sep)
        indent = ' ' * 4 * (level)
        print('{}{}/'.format(indent, os.path.basename(root)))
        subindent = ' ' * 4 * (level + 1)
        for f in files[:5]: # 只显示前5个文件
            print('{}{}'.format(subindent, f))
else:
    print("🎉 数据准备完美就绪！请继续运行 Step 3。")

import os
import shutil

nested_dir = '/content/jax3d/jax3d/projects/mobilenerf/data/custom/MyNeRFData/MyNeRFData'
target_dir = '/content/jax3d/jax3d/projects/mobilenerf/data/custom/MyNeRFData'

print("🔧 正在检测是否套娃...")

if os.path.exists(nested_dir):
    print(f"⚠️ 发现套娃文件夹！正在把文件从 {nested_dir} 搬出来...")

    # 遍历套娃文件夹里的所有文件，移动到外面
    for filename in os.listdir(nested_dir):
        src = os.path.join(nested_dir, filename)
        dst = os.path.join(target_dir, filename)

        # 如果目标已存在，先删除，防止报错
        if os.path.exists(dst):
            if os.path.isdir(dst): shutil.rmtree(dst)
            else: os.remove(dst)

        shutil.move(src, dst)
        print(f"  -> 移动: {filename}")

    # 删掉空的套娃壳子
    os.rmdir(nested_dir)
    print("✅ 搬家完成！结构已修复。")
else:
    print("ℹ️ 没发现套娃文件夹。")
    # 检查一下文件到底在哪
    if os.path.exists(os.path.join(target_dir, "transforms_train.json")):
        print("✅ 确认：json 文件已经在正确位置了。")
    else:
        print("❌ 依然找不到文件，请检查左侧文件栏确认路径。")

import os
import time
import threading
import shutil
import re
from google.colab import drive
from IPython import get_ipython

# 1. 环境准备
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

project_dir = '/content/jax3d/jax3d/projects/mobilenerf'
if os.path.exists(project_dir):
    os.chdir(project_dir)
    os.environ['PYTHONPATH'] += ":/content/jax3d"
else:
    print(f"❌ 找不到项目目录: {project_dir}")

"""# Cell 4: Stage1 备份 + Stage2 代码修复入口"""

# ==============================================================================
# Stage 2 强制修复脚本 (无论如何都要把 0.033 塞进去！)
# ==============================================================================
import os

PROJECT_ROOT = "/content/jax3d/jax3d/projects/mobilenerf"
target_file = os.path.join(PROJECT_ROOT, 'stage2.py')
LOCAL_SAMPLES_DIR = os.path.join(PROJECT_ROOT, "samples_stage2")
# 你的 Drive 输出路径
DRIVE_OUTPUT_DIR = "/content/drive/MyDrive/Stage1_12Jan/Stage2_Result_256"

print(f"🔧 正在暴力修复 {target_file} ...")

with open(target_file, 'r') as f:
    lines = f.readlines()

new_lines = []
scale_injected = False

for line in lines:
    # 1. 强制修改分辨率为 256
    if "point_grid_size =" in line and "128" in line:
        line = "    point_grid_size = 256 # [Force 256]\n"
        print("   ✅ 分辨率已强制改为 256")

    # 2. 强制修改 Samples 路径
    if "os.path.join(base_dir, 'samples')" in line:
        line = line.replace("os.path.join(base_dir, 'samples')", f"'{LOCAL_SAMPLES_DIR}'")
    if "os.path.join(logdir, 'samples')" in line:
        line = line.replace("os.path.join(logdir, 'samples')", f"'{LOCAL_SAMPLES_DIR}'")

    # 3. 🔥 核心：在 return 之前强制插入 Scale 0.033
    # 我们寻找这一行，一旦找到，就在它前面插队
    if "return {'images' : images" in line and not scale_injected:
        print("   🔥 [重要] 正在注入 Scale 0.033 代码...")
        # 写入缩放逻辑
        new_lines.append("\n    # [FORCE INJECTED SCALE]\n")
        new_lines.append("    print('⚡⚡⚡ APPLYING SCALE 0.033 ⚡⚡⚡')\n")
        new_lines.append("    poses = poses.at[:, :3, 3].set(poses[:, :3, 3] * 0.033)\n")
        new_lines.append(line) # 把原来的 return 写回去
        scale_injected = True
        continue

    # 4. 修复 Stage 1 权重读取路径 (防止读不到)
    if "pickle.load" in line and "weights_stage1.pkl" in line:
        line = "    vars = pickle.load(open('weights/weights_stage1.pkl', 'rb'))\n"
        print("   ✅ 权重读取路径已修正")

    new_lines.append(line)

# 写回文件
with open(target_file, 'w') as f:
    f.writelines(new_lines)

if scale_injected:
    print("\n🎉 修复成功！0.033 缩放代码已强制写入。")
else:
    print("\n❌ 严重错误：没找到注入点！请检查 stage2.py 内容。")

"""  # Cell 5: 简易版 Stage1 启动（备份 + 训练）"""

# ==============================================================================
# 🛡️ Stage1 Step 1: 强盗备份脚本
# ==============================================================================
local_checkpoints = "checkpoints"
local_weights = "weights"
local_samples = "samples"

drive_root = "/content/drive/MyDrive/Stage1_12Jan"
drive_checkpoints = os.path.join(drive_root, "checkpoints")
drive_weights = os.path.join(drive_root, "weights")
drive_samples = os.path.join(drive_root, "samples")

def background_backup():
    print("🛡️ 后台备份服务已启动...")
    while True:
        try:
            if os.path.exists(local_checkpoints):
                if not os.path.exists(drive_checkpoints): os.makedirs(drive_checkpoints)
                os.system(f"cp -ru '{local_checkpoints}/.' '{drive_checkpoints}/'")
            if os.path.exists(local_weights):
                if not os.path.exists(drive_weights): os.makedirs(drive_weights)
                os.system(f"cp -ru '{local_weights}/.' '{drive_weights}/'")
            if os.path.exists(local_samples):
                if not os.path.exists(drive_samples): os.makedirs(drive_samples)
                os.system(f"cp -ru '{local_samples}/.' '{drive_samples}/'")
        except:
            pass
        time.sleep(30)

t = threading.Thread(target=background_backup)
t.daemon = True
t.start()

# ==============================================================================
# 🚀 Stage1 Step 2: 启动训练
# ==============================================================================
print("🚀 启动训练...")

cmd = """
source activate mobilenerf && export MPLBACKEND=Agg && python stage1.py \
  --gin_configs=configs/360.gin \
  --gin_bindings="Config.dataset_loader='blender'" \
  --gin_bindings="Config.batch_size=4096" \
  --gin_bindings="Config.data_dir='/content/jax3d/jax3d/projects/mobilenerf/data/custom/MyNeRFData'" \
  --gin_bindings="Config.checkpoint_dir='/content/jax3d/jax3d/projects/mobilenerf/checkpoints'" \
  --gin_bindings="Config.render_every=1000" \
  --gin_bindings="Config.save_every=2000" \
  --logtostderr
"""

get_ipython().system(cmd)

"""# Cell 6: Stage2 适配 .pkl 存档 + Scale 0.033"""

# ==============================================================================
# 🛡️ Stage 2 复刻修正版 (修复路径 + Scale 0.033 + Res 256)
# ==============================================================================
import os
import re
import pickle
import shutil
import glob
from google.colab import drive
from IPython import get_ipython

# --- 1. 路径与参数配置 ---
# Drive 源头 (Stage 1 权重)
DRIVE_SOURCE_PKL_DIR = "/content/drive/MyDrive/Stage1_12Jan/weights"
# Drive 输出 (Stage 2 结果) - 直接存这里防断连
DRIVE_OUTPUT_DIR = "/content/drive/MyDrive/Stage1_12Jan/Stage2_Result_256"

# 本地路径
PROJECT_ROOT = "/content/jax3d/jax3d/projects/mobilenerf"
LOCAL_WEIGHTS_DIR = os.path.join(PROJECT_ROOT, "weights")
LOCAL_SAMPLES_DIR = os.path.join(PROJECT_ROOT, "samples_stage2")

# 关键参数
TARGET_SCALE = 0.033
TARGET_GRID = 256

# ==============================================================================
# Stage2 [Step 1] 环境准备
# ==============================================================================
print("🚚 [1/4] 环境准备中...")

if not os.path.exists('/content/drive'): drive.mount('/content/drive')
if not os.path.exists(LOCAL_WEIGHTS_DIR): os.makedirs(LOCAL_WEIGHTS_DIR)
if not os.path.exists(LOCAL_SAMPLES_DIR): os.makedirs(LOCAL_SAMPLES_DIR)
if not os.path.exists(DRIVE_OUTPUT_DIR): os.makedirs(DRIVE_OUTPUT_DIR)

# 搬运权重 (确保 weights/weights_stage1.pkl 存在)
print(f"    📥 正在查找 Stage 1 权重...")
pkl_files = glob.glob(os.path.join(DRIVE_SOURCE_PKL_DIR, "*.pkl"))
if not pkl_files:
    pkl_files = glob.glob(os.path.join(os.path.dirname(DRIVE_SOURCE_PKL_DIR), "*.pkl"))

if pkl_files:
    pkl_files.sort(key=os.path.getmtime)
    target_pkl = pkl_files[-1]
    shutil.copy2(target_pkl, os.path.join(LOCAL_WEIGHTS_DIR, "weights_stage1.pkl"))
    print(f"      -> 已就位: {os.path.basename(target_pkl)}")
else:
    print("❌ 错误：Drive 里没找到 .pkl 文件！")
    assert False

# ==============================================================================
# Stage2 [Step 2] 代码手术（路径与采样配置）
# ==============================================================================
target_file = os.path.join(PROJECT_ROOT, 'stage2.py')
print(f"💉 [2/4] 修改代码...")

with open(target_file, 'r') as f:
    content = f.read()

# 1. 基础修复
content = re.sub(r'object_name = "chair"', 'object_name = "MyNeRFData"', content)
content = re.sub(r'scene_dir = "datasets/nerf_synthetic/.*?\+object_name', 'scene_dir = "data/custom/"+object_name', content)
content = content.replace("import matplotlib.pyplot as plt", "import matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt")

# 3. 修正 Samples 输出路径
content = content.replace("os.path.join(base_dir, 'samples')", f"'{LOCAL_SAMPLES_DIR}'")
content = content.replace("os.path.join(logdir, 'samples')", f"'{LOCAL_SAMPLES_DIR}'")

# 4. [关键修改] 升级分辨率到 256
if "point_grid_size = 128" in content:
    content = content.replace("point_grid_size = 128", f"point_grid_size = {TARGET_GRID} # [A100 Force]")
    print(f"    ✅ 分辨率已修改为 {TARGET_GRID}")

# 5. [关键修改] 注入 Scale 0.033
original_return = "return {'images' : images, 'c2w' : poses, 'hwf' : hwf}"
if "poses[:, :3, 3] * " + str(TARGET_SCALE) not in content:
    injection_code = f"""
    # [Auto-Scale Injection]
    print("⚡ Applying Scale {TARGET_SCALE}...")
    poses = poses.at[:, :3, 3].set(poses[:, :3, 3] * {TARGET_SCALE})
    {original_return}
    """
    content = content.replace(original_return, injection_code)
    print(f"    ✅ Scale {TARGET_SCALE} 注入代码已插入")

# 6. 修复 Stage 1 权重读取 (确保读 weights/weights_stage1.pkl)
# 原代码可能是 pickle.load(open(weights_dir+"/"+"weights_stage1.pkl", "rb"))
# 我们直接硬改
if 'weights_stage1.pkl' in content:
    # 这里的正则稍微宽泛一点，匹配 open(...) 里的内容
    content = re.sub(r'open\(.*?"weights_stage1\.pkl".*?,', 'open("weights/weights_stage1.pkl",', content)

with open(target_file, 'w') as f:
    f.write(content)

# ==============================================================================
# Stage2 [Step 3] 启动 Stage 2
# ==============================================================================
print(f"\n🚀 [3/4] 启动 Stage 2 ...")
print(f"    💾 存档将直接写入: {DRIVE_OUTPUT_DIR}")

os.chdir(PROJECT_ROOT)

# 启动命令
cmd = f"""
source activate mobilenerf && export MPLBACKEND=Agg && python stage2.py \
  --gin_configs=configs/360.gin \
  --gin_bindings="Config.dataset_loader='blender'" \
  --gin_bindings="Config.batch_size=2048" \
  --gin_bindings="Config.data_dir='data/custom/MyNeRFData'" \
  --gin_bindings="Config.checkpoint_dir='{DRIVE_OUTPUT_DIR}'" \
  --logtostderr
"""

get_ipython().system(cmd)

# ==============================================================================
# Stage2 [Step 4] 额外备份 Samples
# ==============================================================================
print("\n📦 [4/4] 备份 Samples 图片...")
if os.path.exists(LOCAL_SAMPLES_DIR):
    drive_sample_dest = DRIVE_OUTPUT_DIR + "_samples"
    if not os.path.exists(drive_sample_dest): os.makedirs(drive_sample_dest)
    os.system(f"cp -r '{LOCAL_SAMPLES_DIR}/.' '{drive_sample_dest}/'")

"""# Cell 7: Stage3 提取 Mesh 与纹理（适配 Drive 读取 + 独立输出）"""

# ==============================================================================
# 🏛️ Stage 3 最终版（接力权重导出 Mesh + 纹理）
# ==============================================================================
import os
import re
import shutil
from google.colab import drive
from IPython import get_ipython

# --- 1. 路径配置 ---
PROJECT_ROOT = "/content/jax3d/jax3d/projects/mobilenerf"

# 关键：读取刚才 Stage 2 刚生成的新权重 (本地)
LOCAL_S2_WEIGHTS_READ = os.path.join(PROJECT_ROOT, "weights")

# 输出路径
LOCAL_S3_OBJ_SAVE = os.path.join(PROJECT_ROOT, "obj_stage3_256")
LOCAL_S3_SAMPLES_SAVE = os.path.join(PROJECT_ROOT, "samples_stage3_256")

# Drive 备份路径
DRIVE_FINAL_EXPORT = "/content/drive/MyDrive/Stage1_12Jan/Final_Sponza_256"

# ================= Step 1: 环境准备 & 权重检查 =================
print("🚚 [1/4] 正在检查权重...")

# 确保输出目录存在
if not os.path.exists(LOCAL_S3_OBJ_SAVE): os.makedirs(LOCAL_S3_OBJ_SAVE)
if not os.path.exists(LOCAL_S3_SAMPLES_SAVE): os.makedirs(LOCAL_S3_SAMPLES_SAVE)

# 检查本地是否有刚才 Stage 2 跑出来的权重
if not os.path.exists(LOCAL_S2_WEIGHTS_READ):
    print(f"❌ 错误：找不到 Stage 2 的输出目录: {LOCAL_S2_WEIGHTS_READ}")
    print("   请确保刚才的 Stage 2 已经成功跑完！")
    assert False

# 找最新的权重文件
pkl_files = [f for f in os.listdir(LOCAL_S2_WEIGHTS_READ) if f.endswith(".pkl")]
if not pkl_files:
    print(f"❌ 错误：在 {LOCAL_S2_WEIGHTS_READ} 里没找到 .pkl 文件！")
    assert False

# 排序找到最新的 (通常是 checkpoint_20000 这种)
pkl_files.sort(key=lambda x: int(re.search(r'\d+', x).group()) if re.search(r'\d+', x) else 0)
target_pkl = pkl_files[-1]
print(f"   ✅ 锁定 Stage 2 权重: {target_pkl}")

# ⚠️ 关键动作：把这个文件复制一份并在原地改名为 'weights_stage2_1.pkl'
# 因为 Stage 3 代码里通常写死读这个名字，或者读 list 的最后一个
# 为了稳妥，我们手动帮它准备好
dest_pkl = os.path.join(LOCAL_S2_WEIGHTS_READ, "weights_stage2_1.pkl")
shutil.copy2(os.path.join(LOCAL_S2_WEIGHTS_READ, target_pkl), dest_pkl)
print(f"   📦 已准备好标准命名权重: weights_stage2_1.pkl")


# ================= Step 2: 代码精准手术 =================
print("\n💉 [2/4] 修改 Stage 3 代码 (分辨率256 + 盒子0.7)...")

target_file = os.path.join(PROJECT_ROOT, 'stage3.py')
with open(target_file, 'r') as f:
    content = f.read()

# A. 路径修复
content = content.replace('object_name = "chair"', 'object_name = "MyNeRFData"')
content = content.replace('scene_dir = "datasets/nerf_synthetic/"+object_name', 'scene_dir = "data/custom/"+object_name')
# 指向我们刚准备好的本地目录
content = content.replace('weights_dir = "weights"', f'weights_dir = "{LOCAL_S2_WEIGHTS_READ}"')
content = content.replace('obj_save_dir = "obj"', f'obj_save_dir = "{LOCAL_S3_OBJ_SAVE}"')
content = content.replace('samples_dir = "samples"', f'samples_dir = "{LOCAL_S3_SAMPLES_SAVE}"')

# B. 🔥 关键同步：分辨率必须是 256 (匹配 Stage 2)
if "point_grid_size = 128" in content:
    content = content.replace("point_grid_size = 128", "point_grid_size = 256 # [MATCH STAGE 2]")
    print("   ✅ 分辨率已同步为 256 (匹配权重)")
elif "point_grid_size = 256" in content:
    print("   ✅ 分辨率保持 256")

# C. 🔥 关键优化：盒子大小 Scale 0.7 (适配 1.22m Sponza)
# 1.4m 的盒子装 1.22m 的物体，利用率极高
if "scene_grid_scale = 1.2" in content:
    content = content.replace("scene_grid_scale = 1.2", "scene_grid_scale = 0.7 # [Fit Sponza]")
    print("   ✅ 捕获框优化为 0.7 (紧凑高精)")
elif "scene_grid_scale = 0.2" in content:
    content = content.replace("scene_grid_scale = 0.2", "scene_grid_scale = 0.7 # [Fit Sponza]")
    print("   ✅ 捕获框修正为 0.7")

# D. JAX Scale 注入 (保持 0.033)
if "poses = np.stack(cams, axis=0)" in content:
    content = content.replace("poses[:, :3, 3] *= 0.033", "")
    if ".at[" not in content:
        content = content.replace(
            "poses = np.stack(cams, axis=0)",
            "poses = np.stack(cams, axis=0)\n    poses = poses.at[:, :3, 3].set(poses[:, :3, 3] * 0.033) # [JAX Scale]"
        )

# E. 移除 Testing (加速)
if 'print("Testing")' in content:
    content = content.replace('print("Testing")', '# print("Testing")')
    content = content.replace('for i in tqdm(range(len(data[\'test\'][\'images\']))):', 'for i in []:\n  pass')
    content = content.replace('for p in tqdm(render_poses):', 'for p in []:\n  pass')

with open(target_file, 'w') as f:
    f.write(content)

# ================= Step 3: 启动 =================
print("\n🚀 [3/4] 启动 Stage 3 (High Res Export)...")
os.chdir(PROJECT_ROOT)
cmd = "source activate mobilenerf && export MPLBACKEND=Agg && python stage3.py"

try:
    get_ipython().system(cmd)
    print("\n🎉 Stage 3 提取结束！")
except Exception as e:
    print(f"\n❌ 运行出错: {e}")

# ================= Step 4: 备份 =================
print("\n📦 [4/4] 备份最终结果到 Drive...")
if not os.path.exists('/content/drive'): drive.mount('/content/drive')
if not os.path.exists(DRIVE_FINAL_EXPORT): os.makedirs(DRIVE_FINAL_EXPORT)

if os.path.exists(LOCAL_S3_OBJ_SAVE):
    print(f"   -> 正在备份 OBJ/GLB 到: {DRIVE_FINAL_EXPORT}")
    os.system(f"cp -r '{LOCAL_S3_OBJ_SAVE}/.' '{DRIVE_FINAL_EXPORT}/'")

    # 备份 Phone 版
    phone_src = LOCAL_S3_OBJ_SAVE + "_phone"
    if os.path.exists(phone_src):
        phone_dst = os.path.join(DRIVE_FINAL_EXPORT, "obj_phone")
        if not os.path.exists(phone_dst): os.makedirs(phone_dst)
        os.system(f"cp -r '{phone_src}/.' '{phone_dst}/'")

print(f"\n✅ 全部完成！高精度 Sponza 已保存至: {DRIVE_FINAL_EXPORT}")

"""# Cell 7: Hybrid 代码拉取（独立于 JAX 环境）
"""

"""# Cell 7: Hybrid 代码拉取（独立于 JAX 环境）"""
# 用途：
# - 仅为 Hybrid 01/02、诊断脚本、xatlas 工具提供代码目录
# 使用场景：
# - 如果你只跑 Hybrid Pipeline，可以跳过前面的 JAX Stage1/2 相关 Cell，从本 Cell 开始

import os
import shutil

MY_REPO_HYBRID = "https://github.com/Davecodingking/jax3d_David.git"
TARGET_DIR_HYBRID = "/content/jax3d"

print("🚀 [Hybrid Repo] 正在准备 jax3d_David 代码（供 01/02 使用）...")

if os.path.exists(TARGET_DIR_HYBRID) or os.path.exists("/content/jax3d_David"):
    print("ℹ️ 检测到现有代码目录，将直接复用当前版本。")
else:
    print(f"📥 正在克隆仓库: {MY_REPO_HYBRID}")
    !git clone {MY_REPO_HYBRID}
    if os.path.exists("/content/jax3d_David"):
        shutil.move("/content/jax3d_David", TARGET_DIR_HYBRID)
        print("✅ 代码已就位 (jax3d_David -> jax3d)")
    else:
        print("❌ 克隆失败，请检查 GitHub 仓库地址或网络连接。")

"""# Cell 8: 环境配置 （PyTorch 2.1 + NumPy 1.26 + PyTorch3D Wheel）
"""

"""# Cell 8-UV: 01_preprocess_raster 专用环境（Wheel加速 + NumPy修复版）"""
# 用途：
# - 给 01_preprocess_raster.py、各类 PyTorch3D 诊断脚本、xatlas 对比脚本提供独立环境
# 何时需要运行：
# - 每次 Colab Runtime 全新启动 / 断线重连后，第一次跑 Hybrid / 诊断 / xatlas 前运行 1 次
# - 已在当前会话成功创建过 hybrid_uv_wheel 时，可以跳过本 Cell

import os

# 1. 创建环境 (Python 3.10)
print("🚀 [Hybrid UV Env] 正在创建 Python 3.10 环境...")
!conda create -n hybrid_uv_wheel python=3.10 -y

# 2. 安装 PyTorch 2.1.0 + CUDA 11.8 + ★NumPy 1.26.4★
# 关键修复：显式加上 numpy=1.26.4，防止安装 NumPy 2.x
print("⏳ 正在安装 PyTorch 2.1.0 和 NumPy 1.26.4...")
!source activate hybrid_uv_wheel && conda install -y \
    pytorch=2.1.0 torchvision=0.16.0 torchaudio=2.1.0 \
    pytorch-cuda=11.8 \
    numpy=1.26.4 \
    -c pytorch -c nvidia

# 3. 安装依赖 (fvcore, iopath)
# 使用 pip 安装时也限制 numpy 版本，防止被升级
print("⏳ 正在安装基础依赖...")
!source activate hybrid_uv_wheel && pip install "numpy<2" fvcore iopath matplotlib pillow


# 4. 安装 PyTorch3D 官方 Wheel 包 (GPU 加速核心)
print("⏳ 正在安装 PyTorch3D 官方加速包...")
!source activate hybrid_uv_wheel && pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu118_pyt210/download.html

print("\n✅ 环境配置完成！NumPy版本已锁定，CUDA加速已就绪。")

"""# Cell 8: Hybrid Workflow 环境配置（基于 Colab 默认环境）"""
# 用途：
# - 在 Colab 默认 Python 环境中安装 Torch + PyTorch3D，供 02_train_hybrid.py 使用
# 何时需要运行：
# - 每次 Colab Runtime 全新启动 / 断线重连后，第一次跑 Hybrid 训练（Cell 10/11）前运行 1 次
# - 如果当前会话已经安装过 torch / pytorch3d，本 Cell 可跳过

print("\n🚀 [Hybrid Env] 配置 Torch + PyTorch3D 环境（使用 Colab 默认 Python）...")
!pip install --upgrade pip
!pip install "numpy<2"
!pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html

# !pip install --upgrade pip
# !pip install "numpy<2" --force-reinstall
# !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html

"""# Cell 9:Hybrid Pipeline Step 1 - 预计算 UV (PyTorch3D)"""

"""# Cell 9: Hybrid Pipeline Step 1 - 预计算 UV (运行)"""
# 作用：
# - 在 hybrid_uv_wheel 环境中调用 01_preprocess_raster.py，生成 uv_lookup.npz
# 何时需要运行：
# - 第一次为当前 MyNeRFData 场景生成 UV 映射时必须运行
# - 若修改了 OBJ / transforms_*，需要重新运行以更新 uv_lookup.npz
# - 若 Colab 重启但 Drive 中已有 uv_lookup.npz，可依赖 Cell 10/11 自动从 Drive 恢复，本 Cell 可选

import os
from IPython import get_ipython
from google.colab import drive
import numpy as np

PROJECT_ROOT_HYBRID = "/content/jax3d/jax3d/projects/mobilenerf"
DRIVE_HYBRID_ROOT = "/content/drive/MyDrive/Hybrid_Pipeline"
HYBRID_DATA_ROOT = "data/custom/MyNeRFData"
HYBRID_OBJ_NAME = "sponza_gt_unwarpped.obj"
HYBRID_TRANSFORMS = "transforms_train.json"
HYBRID_UV_OUTPUT = "uv_lookup.npz"

print("\n🚀 [Hybrid 1/2] 预计算 UV 映射 (GPU 加速模式)...")

if not os.path.exists("/content/drive"):
    drive.mount("/content/drive")

if not os.path.exists(DRIVE_HYBRID_ROOT):
    os.makedirs(DRIVE_HYBRID_ROOT)

if os.path.exists(PROJECT_ROOT_HYBRID):
    os.chdir(PROJECT_ROOT_HYBRID)

    # 注意：这里激活的是 hybrid_uv_wheel 环境
    cmd = f"""
    source activate hybrid_uv_wheel && \
    python 01_preprocess_raster.py \
      --data_root='{HYBRID_DATA_ROOT}' \
      --obj_name='{HYBRID_OBJ_NAME}' \
      --transforms='{HYBRID_TRANSFORMS}' \
      --output='{HYBRID_UV_OUTPUT}' \
      --downscale=1 \
      --device='cuda'
    """

    get_ipython().system(f"bash -c '{cmd}'")

    uv_path = os.path.join(PROJECT_ROOT_HYBRID, HYBRID_DATA_ROOT, HYBRID_UV_OUTPUT)
    if os.path.exists(uv_path):
        data = np.load(uv_path, allow_pickle=True)
        print(f"✅ UV 映射生成完成，形状: {data['uv'].shape}")
        # 复制到 Google Drive 备份
        os.system(f"cp '{uv_path}' '{DRIVE_HYBRID_ROOT}/'")
        print(f"✅ 备份完成！现在去运行训练吧。")
    else:
        print("⚠️ 未找到 uv_lookup.npz，请检查上方报错")
else:
    print(f"❌ 找不到项目目录: {PROJECT_ROOT_HYBRID}")

"""# Cell 9.2: Overlay 检查 - Forensic (Top-Down + Overlay"""

"""# Cell 9.2: Overlay 检查 - Forensic (Top-Down + Overlay)"""
# 用途：
# - 使用 PyTorch3D 在 hybrid_uv_wheel 环境中做 Top-Down + Overlay 调试，检查模型朝向与相机对齐
# 说明：
# - 完全可选，仅在你需要深入排查几何 / 相机问题时运行

code_content = r'''
import os
import json
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from pytorch3d.io import load_obj
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    PerspectiveCameras, RasterizationSettings, MeshRasterizer,
    MeshRenderer, HardPhongShader, PointLights, TexturesVertex,
    look_at_view_transform
)

# ================= 配置 =================
DATA_ROOT = "data/custom/MyNeRFData"
OBJ_NAME = "sponza_gt.obj"
TRANSFORMS = "transforms_train.json"
DEVICE = "cuda"
VIEW_INDEX = 0
# =======================================

def forensic_investigation_fixed():
    print("🕵️‍♂️ 启动最终排查 (自动分辨率适配版)...")

    # 1. 准备数据
    json_path = os.path.join(DATA_ROOT, TRANSFORMS)
    if not os.path.exists(json_path):
        print(f"❌ 错误: 找不到 {json_path}")
        return

    with open(json_path, "r") as f:
        meta = json.load(f)
    frame = meta["frames"][VIEW_INDEX]

    # 图片
    img_path = os.path.join(DATA_ROOT, frame["file_path"] + ".png")
    if not os.path.exists(img_path): img_path = img_path.replace(".png", ".jpg")
    gt_image = np.array(Image.open(img_path).convert("RGB")) / 255.0
    H, W, _ = gt_image.shape
    print(f"📷 检测到图像尺寸: {H}x{W}")

    # 模型
    obj_path = os.path.join(DATA_ROOT, OBJ_NAME)
    verts, faces, _ = load_obj(obj_path)
    verts = verts.to(DEVICE).float()
    faces_idx = faces.verts_idx.to(DEVICE).long()

    # 给模型上白色
    verts_rgb = torch.ones_like(verts)[None]
    textures = TexturesVertex(verts_features=verts_rgb)
    mesh = Meshes(verts=[verts], faces=[faces_idx], textures=textures)

    plt.figure(figsize=(16, 8))

    # ★★★ 关键修复：使用 (H, W) 而不是写死 512 ★★★
    raster_settings = RasterizationSettings(
        image_size=(H, W),  # <--- 这里改了，绝对不会再报错
        blur_radius=0.0,
        faces_per_pixel=1,
        cull_backfaces=True
    )

    # -------------------------------------------------------------
    # 视角 A: 上帝视角 (Top-Down View) - 查模型方向
    # -------------------------------------------------------------
    # 放在 Y=50 的高空，往下看 (0,0,0)。
    R_top, T_top = look_at_view_transform(
        dist=50.0,
        elev=90.0,
        azim=0.0,
        device=DEVICE
    )

    cameras_top = PerspectiveCameras(device=DEVICE, R=R_top, T=T_top)
    lights_top = PointLights(device=DEVICE, location=[[0.0, 50.0, 0.0]])

    renderer_top = MeshRenderer(
        rasterizer=MeshRasterizer(cameras=cameras_top, raster_settings=raster_settings),
        shader=HardPhongShader(device=DEVICE, cameras=cameras_top, lights=lights_top)
    )

    img_top = renderer_top(mesh)[0, ..., :3].cpu().numpy()

    plt.subplot(1, 2, 1)
    plt.title(f"A: Top-Down View\n(Is the corridor Horizontal-X or Vertical-Z?)")
    plt.imshow(img_top)
    plt.axis("off")

    # -------------------------------------------------------------
    # 视角 B: 说明书验证 (Standard Unity->PyTorch3D) - 查对齐
    # -------------------------------------------------------------
    # 公式：Flip X

    raw_c2w = np.array(frame["transform_matrix"], dtype=np.float32)
    c2w = raw_c2w.copy()

    # 1. 翻转 X 轴
    #c2w[:3, 0] *= -1
    # 2. 翻转 X 位置
    #c2w[0, 3] *= -1

    c2w_torch = torch.from_numpy(c2w).to(DEVICE).unsqueeze(0)
    w2c = torch.inverse(c2w_torch)

    # 计算透视
    camera_angle_x = float(meta["camera_angle_x"])
    focal = 0.5 * W / np.tan(0.5 * camera_angle_x)

    cameras_std = PerspectiveCameras(
        device=DEVICE, R=w2c[:, :3, :3], T=w2c[:, :3, 3],
        focal_length=((focal, focal),),
        principal_point=((W/2, H/2),),
        image_size=((H, W),),
        in_ndc=False
    )

    lights_std = PointLights(device=DEVICE, location=[[0.0, 0.0, 0.0]])
    renderer_std = MeshRenderer(
        rasterizer=MeshRasterizer(cameras=cameras_std, raster_settings=raster_settings),
        shader=HardPhongShader(device=DEVICE, cameras=cameras_std, lights=lights_std)
    )

    img_std = renderer_std(mesh)[0, ..., :3].cpu().numpy()

    # 叠加验证
    overlay = gt_image.copy()
    mask = img_std.sum(axis=-1) > 0.1
    # 这里的 img_std 现在也是 (H, W)，和 overlay 一样大，不会报错
    overlay[mask] = overlay[mask] * 0.5 + img_std[mask] * 0.5

    plt.subplot(1, 2, 2)
    plt.title("B: Standard 'Flip X' Check")
    plt.imshow(overlay)
    plt.axis("off")

    save_path = "forensic_result_fixed.png"
    plt.savefig(save_path, bbox_inches='tight')
    print(f"✅ 修复完成，图片已生成: {save_path}")

if __name__ == "__main__":
    forensic_investigation_fixed()
'''

with open("debug_investigation_fixed.py", "w") as f:
    f.write(code_content)

print("🚀 正在运行修复版调查脚本...")
!conda run -n hybrid_uv_wheel bash -c "export MPLBACKEND=Agg && python debug_investigation_fixed.py"

if os.path.exists("forensic_result_fixed.png"):
    display(Image("forensic_result_fixed.png"))
else:
    print("❌ 运行失败，请看上面报错")

"""# Cell 9.3: Overlay 检查 无反转"""

import os

# 定义对比脚本内容
diagnostic_script = r'''
import os
import json
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from pytorch3d.io import load_obj
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    PerspectiveCameras, RasterizationSettings, MeshRasterizer,
    MeshRenderer, SoftPhongShader, AmbientLights, TexturesVertex
)

# ================= CONFIG =================
DATA_ROOT = "data/custom/MyNeRFData"
OBJ_NAME = "sponza_gt.obj"
TRANSFORMS = "transforms_train.json"
DEVICE = "cuda"
TARGET_FRAMES = [0, 29] # 第 1 帧 和 第 30 帧
# ==========================================

def run_comparison():
    print(f"🚀 启动结构对比诊断: 检查 Index {TARGET_FRAMES}...")

    # 1. 加载模型
    obj_path = os.path.join(DATA_ROOT, OBJ_NAME)
    verts, faces, _ = load_obj(obj_path)
    verts = verts.to(DEVICE).float()
    faces_idx = faces.verts_idx.to(DEVICE).long()

    # 法线着色：观察几何轮廓
    temp_mesh = Meshes(verts=[verts], faces=[faces_idx])
    normals = temp_mesh.verts_normals_packed()
    verts_rgb = (normals + 1.0) / 2.0
    textures = TexturesVertex(verts_features=verts_rgb[None])
    mesh = Meshes(verts=[verts], faces=[faces_idx], textures=textures)

    # 2. 加载元数据
    with open(os.path.join(DATA_ROOT, TRANSFORMS), "r") as f:
        meta = json.load(f)

    camera_angle_x = float(meta["camera_angle_x"])
    lights = AmbientLights(device=DEVICE, ambient_color=((1.0, 1.0, 1.0),))

    results = []

    for idx in TARGET_FRAMES:
        frame = meta["frames"][idx]
        img_path = os.path.join(DATA_ROOT, frame["file_path"] + ".png")
        if not os.path.exists(img_path):
            img_path = img_path.replace(".png", ".jpg")

        gt_image = np.array(Image.open(img_path).convert("RGB")) / 255.0
        H, W, _ = gt_image.shape

        c2w = np.array(frame["transform_matrix"], dtype=np.float32)
        c2w_t = torch.from_numpy(c2w).to(DEVICE)

        R_c2w = c2w_t[:3, :3]
        C = c2w_t[:3, 3]
        R_w2c = R_c2w.t()
        T_w2c = -R_w2c @ C

        focal = 0.5 * W / np.tan(0.5 * camera_angle_x)
        cameras = PerspectiveCameras(
            device=DEVICE,
            R=R_w2c.t().unsqueeze(0), # PyTorch3D 内部使用行向量乘法，所以传转置
            T=T_w2c.unsqueeze(0),
            focal_length=((focal, focal),),
            principal_point=((W/2, H/2),),
            image_size=((H, W),),
            in_ndc=False
        )

        raster_settings = RasterizationSettings(image_size=(H, W), blur_radius=0.0, faces_per_pixel=1, cull_backfaces=False)
        renderer = MeshRenderer(
            rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
            shader=SoftPhongShader(device=DEVICE, cameras=cameras, lights=lights)
        )

        render_rgba = renderer(mesh)[0].cpu().numpy()
        render_rgb = render_rgba[..., :3]
        results.append((gt_image, render_rgb, idx))

    fig, axes = plt.subplots(2, 2, figsize=(20, 16))
    for i, (gt, ren, idx) in enumerate(results):
        axes[i, 0].imshow(gt)
        axes[i, 0].set_title(f"Frame {idx}: Unity Photo", fontsize=16)
        axes[i, 0].axis("off")

        axes[i, 1].imshow(ren)
        axes[i, 1].set_title(f"Frame {idx}: Pytorch3D Render (Raw)", fontsize=16)
        axes[i, 1].axis("off")

    plt.tight_layout()
    output_name = "frame_comparison_result.png"
    plt.savefig(output_name)
    print(f"✅ 对比图已生成: {output_name}")

if __name__ == "__main__":
    run_comparison()
'''

# 写入文件
with open("compare_script.py", "w") as f:
    f.write(diagnostic_script)

# 执行诊断
print("🚀 正在运行对比诊断...")
!source activate hybrid_uv_wheel && export MPLBACKEND=Agg && python compare_script.py

# 显示结果
from IPython.display import Image, display
if os.path.exists("frame_comparison_result.png"):
    display(Image("frame_comparison_result.png"))

#诊断

import os

# 定义对比脚本内容
diagnostic_script = r'''
import os
import json
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from pytorch3d.io import load_obj
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    PerspectiveCameras, RasterizationSettings, MeshRasterizer,
    MeshRenderer, SoftPhongShader, AmbientLights, TexturesVertex
)

# ================= CONFIG =================
DATA_ROOT = "data/custom/MyNeRFData"
OBJ_NAME = "sponza_gt.obj"
TRANSFORMS = "transforms_train.json"
DEVICE = "cuda"
TARGET_FRAMES = [0, 29] # 第 1 帧 和 第 30 帧
# ==========================================

def run_comparison():
    print(f"🚀 启动结构对比诊断: 检查 Index {TARGET_FRAMES}...")

    # 1. 加载模型
    obj_path = os.path.join(DATA_ROOT, OBJ_NAME)
    verts, faces, _ = load_obj(obj_path)
    verts = verts.to(DEVICE).float()
    faces_idx = faces.verts_idx.to(DEVICE).long()

    # 法线着色：观察几何轮廓
    temp_mesh = Meshes(verts=[verts], faces=[faces_idx])
    normals = temp_mesh.verts_normals_packed()
    verts_rgb = (normals + 1.0) / 2.0
    textures = TexturesVertex(verts_features=verts_rgb[None])
    mesh = Meshes(verts=[verts], faces=[faces_idx], textures=textures)

    # 2. 加载元数据
    with open(os.path.join(DATA_ROOT, TRANSFORMS), "r") as f:
        meta = json.load(f)

    camera_angle_x = float(meta["camera_angle_x"])
    lights = AmbientLights(device=DEVICE, ambient_color=((1.0, 1.0, 1.0),))

    conversions = [
        ("world_flip_z", "world", np.diag([1.0, 1.0, -1.0, 1.0]).astype(np.float32)),
        ("world_flip_x", "world", np.diag([-1.0, 1.0, 1.0, 1.0]).astype(np.float32)),
        ("camera_flip_z", "camera", np.diag([1.0, 1.0, -1.0, 1.0]).astype(np.float32)),
        ("camera_flip_x", "camera", np.diag([-1.0, 1.0, 1.0, 1.0]).astype(np.float32)),
    ]

    for name, mode, S in conversions:
        results = []

        for idx in TARGET_FRAMES:
            frame = meta["frames"][idx]
            img_path = os.path.join(DATA_ROOT, frame["file_path"] + ".png")
            if not os.path.exists(img_path):
                img_path = img_path.replace(".png", ".jpg")

            gt_image = np.array(Image.open(img_path).convert("RGB")) / 255.0
            H, W, _ = gt_image.shape

            # --- [矩阵转换：坐标系切换] ---
            c2w = np.array(frame["transform_matrix"], dtype=np.float32)
            if mode == "world":
                c2w = S @ c2w
            else:
                c2w = c2w @ S
            c2w_t = torch.from_numpy(c2w).to(DEVICE)

            # 1. 计算 W2C (R = R_c2w.T, T = -R_w2c * Pos)
            R_c2w = c2w_t[:3, :3]
            C = c2w_t[:3, 3]
            R_w2c = R_c2w.t()
            T_w2c = -R_w2c @ C

            focal = 0.5 * W / np.tan(0.5 * camera_angle_x)
            cameras = PerspectiveCameras(
                device=DEVICE,
                R=R_w2c.t().unsqueeze(0), # PyTorch3D 内部使用行向量乘法，所以传转置
                T=T_w2c.unsqueeze(0),
                focal_length=((focal, focal),),
                principal_point=((W/2, H/2),),
                image_size=((H, W),),
                in_ndc=False
            )

            # 3. 渲染
            raster_settings = RasterizationSettings(image_size=(H, W), blur_radius=0.0, faces_per_pixel=1, cull_backfaces=False)
            renderer = MeshRenderer(
                rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
                shader=SoftPhongShader(device=DEVICE, cameras=cameras, lights=lights)
            )

            render_rgba = renderer(mesh)[0].cpu().numpy()
            render_rgb = render_rgba[..., :3]
            results.append((gt_image, render_rgb, idx))

        # 4. 绘图展示
        fig, axes = plt.subplots(2, 2, figsize=(20, 16))
        for i, (gt, ren, idx) in enumerate(results):
            axes[i, 0].imshow(gt)
            axes[i, 0].set_title(f"Frame {idx}: Unity Photo", fontsize=16)
            axes[i, 0].axis("off")

            axes[i, 1].imshow(ren)
            axes[i, 1].set_title(f"Frame {idx}: Pytorch3D Render ({name})", fontsize=16)
            axes[i, 1].axis("off")

        plt.tight_layout()
        output_name = f"frame_comparison_result_{name}.png"
        plt.savefig(output_name)
        print(f"✅ 对比图已生成: {output_name}")

if __name__ == "__main__":
    run_comparison()
'''

# 写入文件
with open("compare_script.py", "w") as f:
    f.write(diagnostic_script)

# 执行诊断
print("🚀 正在运行坐标系切换对比诊断...")
!source activate hybrid_uv_wheel && export MPLBACKEND=Agg && python compare_script.py

# 显示结果
from IPython.display import Image, display
for name in ["world_flip_z", "world_flip_x", "camera_flip_z", "camera_flip_x"]:
    output_name = f"frame_comparison_result_{name}.png"
    if os.path.exists(output_name):
        display(Image(output_name))

"""# Cell 9.1: 使用 xatlas 修复 UV 重叠并导出 OBJ"""

"""# Cell 9.1: 使用 xatlas 修复 UV 重叠并导出 OBJ"""
# 用途：
# - 调用 uv_unwrap_xatlas.py，对原始 OBJ 做 UV 重映射，生成 sponza_gt_unwarpped.obj
# 说明：
# - 仅当你需要重新生成 unwrapped OBJ（或验证 xatlas 结果）时运行
# - 生成的新 OBJ 会自动备份到 Drive

print("\n🚀 [Hybrid 1/2 Extra] xatlas UV 重映射（保持顶点顺序/位置不变）...")
!source activate hybrid_uv_wheel && pip install xatlas trimesh

PROJECT_ROOT_HYBRID = "/content/jax3d/jax3d/projects/mobilenerf"
DRIVE_HYBRID_ROOT = "/content/drive/MyDrive/Hybrid_Pipeline"
HYBRID_DATA_ROOT = "data/custom/MyNeRFData"
HYBRID_OBJ_NAME = "sponza_gt.obj"

if os.path.exists(PROJECT_ROOT_HYBRID):
    os.chdir(PROJECT_ROOT_HYBRID)
    cmd = f"""
    source activate hybrid_uv_wheel && \
    python uv_unwrap_xatlas.py --input {HYBRID_DATA_ROOT}/{HYBRID_OBJ_NAME} --output {HYBRID_DATA_ROOT}/sponza_gt_unwarpped.obj
    """
    get_ipython().system(f"bash -c '{cmd}'")

    new_obj = os.path.join(PROJECT_ROOT_HYBRID, HYBRID_DATA_ROOT, "sponza_gt_unwarpped.obj")
    if os.path.exists(new_obj):
        print("✅ xatlas UV 重映射完成，已生成 sponza_gt_unwarpped.obj")
        os.system(f"cp '{new_obj}' '{DRIVE_HYBRID_ROOT}/'")
        print("✅ 已备份到 Drive")
    else:
        print("❌ xatlas 重映射输出不存在，请检查日志")
else:
    print(f"❌ 找不到项目目录: {PROJECT_ROOT_HYBRID}")

import os

# 定义对比脚本内容
diagnostic_script = r'''
import os
import json
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from pytorch3d.io import load_obj
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    PerspectiveCameras, RasterizationSettings, MeshRasterizer,
    MeshRenderer, SoftPhongShader, AmbientLights, TexturesVertex
)

# ================= CONFIG =================
DATA_ROOT = "data/custom/MyNeRFData"
OBJ_NAME = "sponza_gt_unwarpped.obj"
TRANSFORMS = "transforms_train.json"
DEVICE = "cuda"
TARGET_FRAMES = [0, 29] # 第 1 帧 和 第 30 帧
# ==========================================

def run_comparison():
    print(f"🚀 启动结构对比诊断: 检查 Index {TARGET_FRAMES}...")

    # 1. 加载模型
    obj_path = os.path.join(DATA_ROOT, OBJ_NAME)
    verts, faces, _ = load_obj(obj_path)
    verts = verts.to(DEVICE).float()
    faces_idx = faces.verts_idx.to(DEVICE).long()

    # 法线着色：观察几何轮廓
    temp_mesh = Meshes(verts=[verts], faces=[faces_idx])
    normals = temp_mesh.verts_normals_packed()
    verts_rgb = (normals + 1.0) / 2.0
    textures = TexturesVertex(verts_features=verts_rgb[None])
    mesh = Meshes(verts=[verts], faces=[faces_idx], textures=textures)

    # 2. 加载元数据
    with open(os.path.join(DATA_ROOT, TRANSFORMS), "r") as f:
        meta = json.load(f)

    camera_angle_x = float(meta["camera_angle_x"])
    lights = AmbientLights(device=DEVICE, ambient_color=((1.0, 1.0, 1.0),))

    results = []

    for idx in TARGET_FRAMES:
        frame = meta["frames"][idx]
        img_path = os.path.join(DATA_ROOT, frame["file_path"] + ".png")
        if not os.path.exists(img_path):
            img_path = img_path.replace(".png", ".jpg")

        gt_image = np.array(Image.open(img_path).convert("RGB")) / 255.0
        H, W, _ = gt_image.shape

        c2w = np.array(frame["transform_matrix"], dtype=np.float32)
        c2w_t = torch.from_numpy(c2w).to(DEVICE)

        R_c2w = c2w_t[:3, :3]
        C = c2w_t[:3, 3]
        R_w2c = R_c2w.t()
        T_w2c = -R_w2c @ C

        focal = 0.5 * W / np.tan(0.5 * camera_angle_x)
        cameras = PerspectiveCameras(
            device=DEVICE,
            R=R_w2c.t().unsqueeze(0), # PyTorch3D 内部使用行向量乘法，所以传转置
            T=T_w2c.unsqueeze(0),
            focal_length=((focal, focal),),
            principal_point=((W/2, H/2),),
            image_size=((H, W),),
            in_ndc=False
        )

        raster_settings = RasterizationSettings(image_size=(H, W), blur_radius=0.0, faces_per_pixel=1, cull_backfaces=False)
        renderer = MeshRenderer(
            rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
            shader=SoftPhongShader(device=DEVICE, cameras=cameras, lights=lights)
        )

        render_rgba = renderer(mesh)[0].cpu().numpy()
        render_rgb = render_rgba[..., :3]
        results.append((gt_image, render_rgb, idx))

    fig, axes = plt.subplots(2, 2, figsize=(20, 16))
    for i, (gt, ren, idx) in enumerate(results):
        axes[i, 0].imshow(gt)
        axes[i, 0].set_title(f"Frame {idx}: Unity Photo", fontsize=16)
        axes[i, 0].axis("off")

        axes[i, 1].imshow(ren)
        axes[i, 1].set_title(f"Frame {idx}: Pytorch3D Render (Raw)", fontsize=16)
        axes[i, 1].axis("off")

    plt.tight_layout()
    output_name = "frame_comparison_result.png"
    plt.savefig(output_name)
    print(f"✅ 对比图已生成: {output_name}")

if __name__ == "__main__":
    run_comparison()
'''

# 写入文件
with open("compare_script.py", "w") as f:
    f.write(diagnostic_script)

# 执行诊断
print("🚀 正在运行对比诊断...")
!source activate hybrid_uv_wheel && export MPLBACKEND=Agg && python compare_script.py

# 显示结果
from IPython.display import Image, display
if os.path.exists("frame_comparison_result.png"):
    display(Image("frame_comparison_result.png"))

"""# Cell 9.2: 渲染对比测试 - render_comparison_test.py'''"""

"""# Cell 9.2: 渲染对比测试 - render_comparison_test.py"""
# 用途：
# - 在 hybrid_uv_wheel 环境中运行 render_comparison_test.py，对比原始 vs unwrapped mesh 的渲染与误差
# 说明：
# - 完全可选，用于确认 UV 重映射没有破坏几何 / 投影

import os
from IPython import get_ipython

PROJECT_ROOT_HYBRID = "/content/jax3d/jax3d/projects/mobilenerf"

print("\n🚀 [Hybrid 1/2 Extra] 运行 render_comparison_test.py 做几何一致性对比...")

if os.path.exists(PROJECT_ROOT_HYBRID):
    os.chdir(PROJECT_ROOT_HYBRID)
    cmd = """
    source activate hybrid_uv_wheel && \
    python render_comparison_test.py
    """
    get_ipython().system(f"bash -c '{cmd}'")
else:
    print(f"❌ 找不到项目目录: {PROJECT_ROOT_HYBRID}")



"""# Cell 11: Hybrid Pipeline Step 2 - 训练 Hybrid Texture + MLP"""
# 作用：
# - 在 Colab 默认 Python 环境中运行 02_train_hybrid.py，训练 Hybrid 纹理 + 小 MLP（手机端运行时模型）
# 前置依赖：
# - Cell 8-UV：至少在本 Runtime 中成功创建过 hybrid_uv_wheel（供 01 / 诊断使用）
# - Cell 8 Hybrid Workflow：本 Runtime 中已安装 torch + pytorch3d（本 Cell 只用到这一环境）
# - uv_lookup.npz 已存在：
#   * 刚通过 Cell 9 生成，或
#   * Drive 中已有一份，本 Cell 会自动从 Drive 恢复到本地
# 运行建议：
# - 每次需要训练 / 继续训练 Hybrid 模型时运行
# - Cell 8 不需要每次都重跑，只在 Colab 重启后重新运行一遍即可

import os
import time
import threading
from IPython import get_ipython
from google.colab import drive

PROJECT_ROOT_HYBRID = "/content/jax3d/jax3d/projects/mobilenerf"
DRIVE_HYBRID_ROOT = "/content/drive/MyDrive/Hybrid_Pipeline"


HYBRID_DATA_ROOT_TRAIN = "data/custom/MyNeRFData"
HYBRID_UV_PATH_TRAIN = os.path.join(HYBRID_DATA_ROOT_TRAIN, "uv_lookup.npz")

HYBRID_TEXTURE_SIZE = 2048
HYBRID_BATCH_SIZE = 1024
HYBRID_NUM_ITERS = 300000
HYBRID_LR = 3e-4
HYBRID_DOWNSCALE_TRAIN = 1

HYBRID_CHECKPOINT_PATH = "weights/hybrid_texture_mlp.pth"
HYBRID_ENV_PYTHON = "python"

print("\n🚀 [Hybrid 2/2] 启动 Hybrid Texture + MLP 训练...")

if not os.path.exists("/content/drive"):
    drive.mount("/content/drive")

if not os.path.exists(DRIVE_HYBRID_ROOT):
    os.makedirs(DRIVE_HYBRID_ROOT)

local_weights = os.path.join(PROJECT_ROOT_HYBRID, "weights")
local_samples = os.path.join(PROJECT_ROOT_HYBRID, "samples")
dst_weights = os.path.join(DRIVE_HYBRID_ROOT, "weights")
dst_samples = os.path.join(DRIVE_HYBRID_ROOT, "samples")

def hybrid_background_backup():
    while True:
        try:
            if os.path.exists(local_weights):
                if not os.path.exists(dst_weights):
                    os.makedirs(dst_weights)
                os.system(f"cp -ru '{local_weights}/.' '{dst_weights}/'")
            if os.path.exists(local_samples):
                if not os.path.exists(dst_samples):
                    os.makedirs(dst_samples)
                os.system(f"cp -ru '{local_samples}/.' '{dst_samples}/'")
        except:
            pass
        time.sleep(60)

t = threading.Thread(target=hybrid_background_backup)
t.daemon = True
t.start()

local_uv_path = os.path.join(PROJECT_ROOT_HYBRID, HYBRID_UV_PATH_TRAIN)
drive_uv_path = os.path.join(DRIVE_HYBRID_ROOT, os.path.basename(HYBRID_UV_PATH_TRAIN))

if not os.path.exists(local_uv_path) and os.path.exists(drive_uv_path):
    os.makedirs(os.path.dirname(local_uv_path), exist_ok=True)
    os.system(f"cp '{drive_uv_path}' '{local_uv_path}'")
    print(f"🔄 已从 Drive 恢复 uv_lookup.npz 到本地: {local_uv_path}")

if os.path.exists(PROJECT_ROOT_HYBRID):
    os.chdir(PROJECT_ROOT_HYBRID)
    cmd = f"""
export MPLBACKEND=Agg && {HYBRID_ENV_PYTHON} 02_train_hybrid.py \
  --data_root='{HYBRID_DATA_ROOT_TRAIN}' \
  --uv_path='{HYBRID_UV_PATH_TRAIN}' \
  --texture_size={HYBRID_TEXTURE_SIZE} \
  --batch_size={HYBRID_BATCH_SIZE} \
  --num_iters={HYBRID_NUM_ITERS} \
  --lr={HYBRID_LR} \
  --device='auto' \
  --downscale={HYBRID_DOWNSCALE_TRAIN} \
  --checkpoint='{HYBRID_CHECKPOINT_PATH}'
"""
    get_ipython().system(cmd)

    print("\n📦 正在备份 Hybrid 训练结果到 Drive...")
    if not os.path.exists(DRIVE_HYBRID_ROOT):
        os.makedirs(DRIVE_HYBRID_ROOT)

    local_weights = os.path.join(PROJECT_ROOT_HYBRID, "weights")
    local_samples = os.path.join(PROJECT_ROOT_HYBRID, "samples")

    if os.path.exists(local_weights):
        dst_weights = os.path.join(DRIVE_HYBRID_ROOT, "weights")
        if not os.path.exists(dst_weights):
            os.makedirs(dst_weights)
        os.system(f"cp -ru '{local_weights}/.' '{dst_weights}/'")

    if os.path.exists(local_samples):
        dst_samples = os.path.join(DRIVE_HYBRID_ROOT, "samples")
        if not os.path.exists(dst_samples):
            os.makedirs(dst_samples)
        os.system(f"cp -ru '{local_samples}/.' '{dst_samples}/'")

    print(f"\n✅ Hybrid 训练结果已保存至: {DRIVE_HYBRID_ROOT}")
else:
    print(f"❌ 找不到项目目录: {PROJECT_ROOT_HYBRID}")

import json
import numpy as np

# 读取你的 JSON
with open("data/custom/MyNeRFData/transforms_train.json", "r") as f:
    data = json.load(f)

# 获取第一帧的矩阵
matrix_data = np.array(data["frames"][0]["transform_matrix"])
print("🔍 第一帧原始矩阵 (JSON):\n", matrix_data)

# 【诊断 1】检查旋转矩阵是否正交 (是否发生了扭曲/剪切)
# 提取前3x3 (旋转部分)
R = matrix_data[:3, :3]
# 计算 R * R_transpose (如果是完美的旋转矩阵，结果应该是单位矩阵 Identity)
ortho_check = np.dot(R, R.T)

print("\n📊 正交性检查 (对角线应为1，其他应接近0):")
print(ortho_check)

# 【诊断 2】检查行列式 (Determinant)
# 如果是旋转矩阵，det 应该是 1。如果是镜像矩阵，det 是 -1。
det = np.linalg.det(R)
print(f"\n📐 行列式 (Determinant): {det:.4f}")
if np.isclose(det, 1.0, atol=1e-3):
    print("   -> ✅ 纯旋转矩阵 (右手/左手系保持一致)")
elif np.isclose(det, -1.0, atol=1e-3):
    print("   -> 🪞 包含镜像 (Flip) 的矩阵")
else:
    print("   -> ❌ 矩阵已变形/缩放 (这就是倾斜的根源！)")

# 【诊断 3】检查位置
pos = matrix_data[:3, 3]
print(f"\n📍 相机位置: {pos}")
